import { spawnSync } from 'node:child_process';
const groups={
 communications:[['chat.test.js'],['notification.test.js'],['support.test.js'],['communication.test.js'],['communicationConcurrency.test.js'],['socketSmoke.test.js']],
 financial:[['paymentVerification.test.js'],['payment.test.js'],['runTestFile.js','ledger.test.js'],['runTestFile.js','refundDispute.test.js'],['refundDisputeHardening.test.js'],['payout.test.js']],
 regression:[['auth.test.js'],['oauth.test.js'],['review.test.js'],['booking.test.js'],['runTestFile.js','pricing.test.js'],['paymentVerification.test.js'],['payment.test.js'],['runTestFile.js','ledger.test.js'],['runTestFile.js','refundDispute.test.js'],['refundDisputeHardening.test.js'],['payout.test.js'],['chat.test.js'],['notification.test.js'],['support.test.js'],['communicationConcurrency.test.js'],['socketSmoke.test.js'],['workerVerification.test.js']],
 all:[['auth.test.js'],['oauth.test.js'],['review.test.js'],['booking.test.js'],['runTestFile.js','pricing.test.js'],['paymentVerification.test.js'],['payment.test.js'],['runTestFile.js','ledger.test.js'],['runTestFile.js','refundDispute.test.js'],['refundDisputeHardening.test.js'],['payout.test.js'],['chat.test.js'],['notification.test.js'],['support.test.js'],['communication.test.js'],['communicationConcurrency.test.js'],['socketSmoke.test.js'],['startupSmoke.test.js'],['workerVerification.test.js']],
};
const selected=groups[process.argv[2]];if(!selected)throw new Error('Unknown suite group.');
for(const [file,...args] of selected){const prefix=file==='runTestFile.js'?'helpers/':'';console.log(`RUN_SUITE=${prefix}${file} ${args.join(' ')}`);const started=Date.now();const result=spawnSync(process.execPath,[`tests/${prefix}${file}`,...args],{cwd:process.cwd(),stdio:'inherit',env:{...process.env}});console.log(`SUITE_DURATION_MS=${Date.now()-started} SUITE_EXIT_CODE=${result.status}`);if(result.status!==0){console.error(`SUITE_FAILED=${file} EXIT_CODE=${result.status}`);process.exitCode=result.status||1;break;}}
