process.env.NODE_ENV='test';process.env.PAYMENT_PROVIDER_MODE='mock';process.env.PAYOUT_PROVIDER_MODE='mock';
import assert from 'node:assert/strict';import request from 'supertest';import jwt from 'jsonwebtoken';
import {startReplicaSetTestEnvironment,stopTestEnvironment,createTestApp} from './helpers/testEnvironment.js';
import User from '../src/models/User.js';import WorkerProfile from '../src/models/WorkerProfile.js';import RefreshToken from '../src/models/RefreshToken.js';import AuditLog from '../src/models/AuditLog.js';import config from '../src/config/env.js';import {hashPassword,comparePassword} from '../src/utils/authUtils.js';
let passed=0,failed=0;const failures=[];async function test(name,fn){try{await fn();passed++;console.log(`PASS ${name}`)}catch(error){failed++;failures.push(`${name}: ${error.message}`);console.error(`FAIL ${name}: ${error.message}`)}}
const registration=(suffix,role='CUSTOMER')=>({name:`Auth ${suffix}`,email:` Auth.${suffix}@Example.Test `,phone:`8${String(suffix).padStart(9,'0')}`.slice(-10),password:'StrongPass123',role});
async function main(){await startReplicaSetTestEnvironment();const app=await createTestApp();try{
 const customerData=registration(1);const customerReg=await request(app).post('/api/auth/register').send(customerData);const workerData=registration(2,'WORKER');const workerReg=await request(app).post('/api/auth/register').send(workerData);
 await test('customer registration succeeds',()=>assert.equal(customerReg.status,201));await test('worker registration succeeds',()=>assert.equal(workerReg.status,201));
 await test('public admin registration rejected',async()=>assert.equal((await request(app).post('/api/auth/register').send(registration(3,'ADMIN'))).status,400));
 await test('public super admin registration rejected',async()=>assert.equal((await request(app).post('/api/auth/register').send(registration(4,'SUPER_ADMIN'))).status,400));
 await test('duplicate email rejected',async()=>assert.equal((await request(app).post('/api/auth/register').send({...registration(5),email:customerData.email,phone:'8555555555'})).status,409));
 await test('email normalization works',async()=>assert.equal((await User.findOne({email:'auth.1@example.test'})).email,'auth.1@example.test'));
 await test('weak password rejected',async()=>assert.equal((await request(app).post('/api/auth/register').send({...registration(6),password:'weak'})).status,400));
 const stored=await User.findOne({email:'auth.1@example.test'}).select('+passwordHash');
 await test('password stored hashed',()=>assert.notEqual(stored.passwordHash,customerData.password));await test('password omitted from registration response',()=>assert.ok(!JSON.stringify(customerReg.body).toLowerCase().includes('password')));
 await test('password compares correctly',async()=>assert.equal(await comparePassword(customerData.password,stored.passwordHash),true));await test('password not double hashed',async()=>assert.equal(await comparePassword(stored.passwordHash,stored.passwordHash),false));
 const customerAgent=request.agent(app);const customerLogin=await customerAgent.post('/api/auth/login').send({email:' AUTH.1@EXAMPLE.TEST ',password:customerData.password});
 await test('customer login succeeds',()=>assert.equal(customerLogin.status,200));await test('access token issued',()=>assert.ok(customerLogin.body.accessToken));await test('refresh token not exposed in body',()=>assert.equal(customerLogin.body.refreshToken,undefined));await test('refresh token issued as httpOnly cookie',()=>assert.ok(customerLogin.headers['set-cookie'].some(v=>v.startsWith('refresh_token=')&&v.includes('HttpOnly'))));
 const pendingWorker=await WorkerProfile.findOne({userId:workerReg.body.user.id});await test('worker profile starts incomplete until submission',()=>assert.equal(pendingWorker.verificationStatus,'INCOMPLETE_PROFILE'));await test('worker starts non-public',()=>assert.equal(pendingWorker.isPubliclyVisible,false));await test('incomplete worker login succeeds',async()=>assert.equal((await request(app).post('/api/auth/login').send({email:'auth.2@example.test',password:workerData.password})).status,200));
 const admin=await User.create({name:'Test Admin',email:'admin.auth@test.local',phone:'8999999999',passwordHash:await hashPassword('AdminPass123'),role:'ADMIN',status:'ACTIVE'});await test('admin login succeeds',async()=>assert.equal((await request(app).post('/api/auth/login').send({email:admin.email,password:'AdminPass123'})).status,200));
 await test('wrong password returns generic 401',async()=>{const r=await request(app).post('/api/auth/login').send({email:'auth.1@example.test',password:'WrongPass123'});assert.equal(r.status,401);assert.equal(r.body.errorCode,'INVALID_CREDENTIALS')});await test('unknown email returns generic 401',async()=>{const r=await request(app).post('/api/auth/login').send({email:'missing@example.test',password:'WrongPass123'});assert.equal(r.status,401);assert.equal(r.body.errorCode,'INVALID_CREDENTIALS')});
 const disabled=await User.create({name:'Disabled',email:'disabled@test.local',phone:'8777777777',passwordHash:await hashPassword('Disabled123'),role:'CUSTOMER',status:'INACTIVE'});await test('disabled account rejected',async()=>assert.equal((await request(app).post('/api/auth/login').send({email:disabled.email,password:'Disabled123'})).status,403));const suspended=await User.create({name:'Suspended',email:'suspended@test.local',phone:'8666666666',passwordHash:await hashPassword('Suspended123'),role:'WORKER',status:'SUSPENDED'});await test('suspended account rejected',async()=>assert.equal((await request(app).post('/api/auth/login').send({email:suspended.email,password:'Suspended123'})).status,403));
 await test('auth me succeeds with cookie',async()=>assert.equal((await customerAgent.get('/api/auth/me')).status,200));await test('auth me rejects missing token',async()=>assert.equal((await request(app).get('/api/auth/me')).status,401));await test('invalid JWT rejected',async()=>assert.equal((await request(app).get('/api/auth/me').set('Authorization','Bearer invalid.jwt.token')).status,401));const expired=jwt.sign({userId:stored._id.toString(),role:'CUSTOMER'},config.JWT_ACCESS_SECRET,{expiresIn:-1});await test('expired JWT rejected',async()=>assert.equal((await request(app).get('/api/auth/me').set('Authorization',`Bearer ${expired}`)).status,401));
 await test('Bearer authentication works',async()=>assert.equal((await request(app).get('/api/auth/me').set('Authorization',`Bearer ${customerLogin.body.accessToken}`)).status,200));
 const refreshCookie=customerLogin.headers['set-cookie'].find(v=>v.startsWith('refresh_token=')).split(';')[0];const refresh1=await request(app).post('/api/auth/refresh').set('Cookie',refreshCookie).send({});await test('refresh cookie rotates successfully',()=>assert.equal(refresh1.status,200));await test('refresh token reuse detected',async()=>assert.equal((await request(app).post('/api/auth/refresh').set('Cookie',refreshCookie).send({})).status,403));
 const logoutAgent=request.agent(app);await logoutAgent.post('/api/auth/login').send({email:'auth.1@example.test',password:customerData.password});const logout=await logoutAgent.post('/api/auth/logout').send({});await test('logout succeeds',()=>assert.equal(logout.status,200));await test('logout clears cookies',()=>assert.ok(logout.headers['set-cookie'].some(v=>v.startsWith('access_token=')&&/Expires=Thu, 01 Jan 1970|Max-Age=0/.test(v))));await test('logged out cookie session rejected',async()=>assert.equal((await logoutAgent.get('/api/auth/me')).status,401));
 await test('customer cannot access admin API',async()=>assert.equal((await request(app).get('/api/admin/payouts').set('Authorization',`Bearer ${customerLogin.body.accessToken}`)).status,403));const workerLogin=await request(app).post('/api/auth/login').send({email:'auth.2@example.test',password:workerData.password});await test('worker cannot access customer booking list',async()=>assert.equal((await request(app).get('/api/v1/bookings/customer').set('Authorization',`Bearer ${workerLogin.body.accessToken}`)).status,403));
 const allowedOrigin=config.CORS_ALLOWED_ORIGINS[0];await test('configured CORS origin allowed',async()=>assert.equal((await request(app).options('/api/auth/login').set('Origin',allowedOrigin).set('Access-Control-Request-Method','POST')).headers['access-control-allow-origin'],allowedOrigin));await test('unapproved CORS origin rejected',async()=>assert.equal((await request(app).options('/api/auth/login').set('Origin','http://evil.test').set('Access-Control-Request-Method','POST')).status,403));
 await test('duplicate registration does not duplicate worker profile',async()=>{await request(app).post('/api/auth/register').send(workerData);assert.equal(await WorkerProfile.countDocuments({userId:workerReg.body.user.id}),1)});await test('customer registration creates no worker profile',async()=>assert.equal(await WorkerProfile.countDocuments({userId:customerReg.body.user.id}),0));await test('registration audit created',async()=>assert.ok(await AuditLog.countDocuments({action:'AUTH_REGISTERED'})>=2));await test('login audit created',async()=>assert.ok(await AuditLog.countDocuments({action:'AUTH_LOGIN_SUCCEEDED'})>=3));await test('refresh tokens stored only as hashes',async()=>assert.ok((await RefreshToken.findOne()).tokenHash.length===64));
 console.log(`AUTH_TESTS_EXECUTED=${passed+failed} AUTH_TESTS_PASSED=${passed} AUTH_TESTS_FAILED=${failed}`);if(passed+failed<35)throw new Error('Auth suite discovered fewer than 35 tests.');if(failed)throw new Error(failures.join('\n'));
 }finally{await stopTestEnvironment();}}
main().catch(error=>{console.error(error);process.exitCode=1});
