process.env.NODE_ENV='test'; process.env.PAYMENT_PROVIDER='mock'; process.env.PAYMENT_PROVIDER_MODE='mock'; process.env.PAYOUT_PROVIDER='mock'; process.env.PAYOUT_PROVIDER_MODE='mock';
import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import request from 'supertest';
import { startReplicaSetTestEnvironment,stopTestEnvironment,createTestApp } from './helpers/testEnvironment.js';
import { createCustomer,createServiceCategory,createApprovedWorker,createPaidBooking,authHeaderFor } from './helpers/testFixtures.js';
import { setRazorpayInstance,resetRazorpayInstance,razorpayProvider } from '../src/services/payments/RazorpayProvider.js';
import config from '../src/config/env.js';
import Booking from '../src/models/Booking.js'; import PaymentOrder from '../src/models/PaymentOrder.js'; import PaymentTransaction from '../src/models/PaymentTransaction.js'; import LedgerTransaction from '../src/models/LedgerTransaction.js'; import WebhookEvent from '../src/models/WebhookEvent.js';
let passed=0,failed=0;const failures=[];async function test(n,f){try{await f();passed++;console.log(`PASS ${n}`)}catch(e){failed++;failures.push(`${n}: ${e.message}`);console.error(`FAIL ${n}: ${e.message}`)}}
async function main(){await startReplicaSetTestEnvironment();const app=await createTestApp();try{
 const customer=await createCustomer(),other=await createCustomer(),category=await createServiceCategory(),worker=await createApprovedWorker({category}); const booking=await createPaidBooking({customer,worker,category,amountPaise:70800}); await Booking.findByIdAndUpdate(booking._id,{bookingStatus:'PAYMENT_PENDING',paymentStatus:'PENDING',escrowStatus:'NOT_FUNDED'}); const snapshot=JSON.stringify(booking.pricingSnapshot);
 setRazorpayInstance({orders:{create:async p=>({id:'order_legacy_test',...p,status:'created'}),fetch:async id=>({id,amount:70800,currency:'INR',status:'paid'})},payments:{fetch:async id=>({id,amount:70800,currency:'INR',status:'captured',captured:true,method:'upi'})}});
 const orderRes=await request(app).post('/api/v1/payments/orders').set(authHeaderFor(customer)).set('Idempotency-Key','legacy-order-key').send({bookingId:booking._id.toString(),amount:1}); const internalId=orderRes.body.data?.internalPaymentOrderId; const order=await PaymentOrder.findById(internalId);
 await test('backend order creation succeeds',()=>assert.equal(orderRes.status,201)); await test('backend order uses booking amount',()=>assert.equal(order.amountPaise,70800)); await test('client amount is ignored',()=>assert.notEqual(order.amountPaise,1));
 await test('cross-customer order creation rejected',async()=>assert.equal((await request(app).post('/api/v1/payments/orders').set(authHeaderFor(other)).set('Idempotency-Key','other-order-key').send({bookingId:booking._id.toString()})).status,403));
 const paymentId='pay_legacy_valid'; const validSig=crypto.createHmac('sha256',config.RAZORPAY_KEY_SECRET).update(`${order.providerOrderId}|${paymentId}`).digest('hex');
 await test('valid checkout signature passes provider check',()=>assert.equal(razorpayProvider.verifyCheckoutSignature(order.providerOrderId,paymentId,validSig),true)); await test('invalid checkout signature fails',()=>assert.equal(razorpayProvider.verifyCheckoutSignature(order.providerOrderId,paymentId,'00'),false));
 await test('provider order mismatch fails',async()=>assert.equal((await request(app).post('/api/v1/payments/verify').set(authHeaderFor(customer)).send({internalPaymentOrderId:internalId,razorpay_order_id:'wrong_order',razorpay_payment_id:paymentId,razorpay_signature:validSig})).status,400));
 const verify=await request(app).post('/api/v1/payments/verify').set(authHeaderFor(customer)).send({internalPaymentOrderId:internalId,razorpay_order_id:order.providerOrderId,razorpay_payment_id:paymentId,razorpay_signature:validSig}); await test('valid checkout verification succeeds',()=>assert.equal(verify.status,200,JSON.stringify(verify.body)));
 const duplicate=await request(app).post('/api/v1/payments/verify').set(authHeaderFor(customer)).send({internalPaymentOrderId:internalId,razorpay_order_id:order.providerOrderId,razorpay_payment_id:paymentId,razorpay_signature:validSig}); await test('duplicate verification is idempotent',()=>assert.equal(duplicate.status,200));
 await test('captured payment updates booking once',async()=>assert.equal((await Booking.findById(booking._id)).paymentStatus,'PAID')); await test('payment preserves pricing snapshot',async()=>assert.equal(JSON.stringify((await Booking.findById(booking._id)).pricingSnapshot),snapshot)); await test('payment funding ledger posts once',async()=>assert.equal(await LedgerTransaction.countDocuments({idempotencyKey:`PAYMENT_CAPTURED:${paymentId}`}),1));
 const webhookPayload={id:'evt_legacy_raw',event:'unknown.payment.event',created_at:Math.floor(Date.now()/1000),payload:{}};const raw=Buffer.from(JSON.stringify(webhookPayload));const webhookSig=crypto.createHmac('sha256',config.RAZORPAY_WEBHOOK_SECRET).update(raw).digest('hex'); const rawResult=await request(app).post('/api/v1/webhooks/razorpay').set('Content-Type','application/json').set('x-razorpay-signature',webhookSig).send(raw.toString()); await test('exact raw webhook signature passes',()=>assert.equal(rawResult.status,200)); const modified=Buffer.from(raw.toString().replace('unknown.payment.event','changed.payment.event')); await test('modified raw webhook fails signature',()=>assert.equal(razorpayProvider.verifyWebhookSignature(modified,webhookSig),false)); await test('duplicate webhook processes once',async()=>{await request(app).post('/api/v1/webhooks/razorpay').set('Content-Type','application/json').set('x-razorpay-signature',webhookSig).send(raw.toString());assert.equal(await WebhookEvent.countDocuments({providerEventId:'evt_legacy_raw'}),1)});
 const unpaid=await createPaidBooking({customer,worker,category,start:new Date(Date.now()+5*86400000)});await Booking.findByIdAndUpdate(unpaid._id,{bookingStatus:'PAYMENT_PENDING',paymentStatus:'PENDING'});await test('worker cannot accept unpaid booking',async()=>assert.equal((await request(app).post(`/api/v1/bookings/${unpaid._id}/accept`).set(authHeaderFor(worker))).status,402));
 await test('legacy suite discovers tests',()=>assert.ok(passed+failed>0)); console.log(`LEGACY_PAYMENT_TESTS_EXECUTED=${passed+failed} LEGACY_PAYMENT_TESTS_PASSED=${passed} LEGACY_PAYMENT_TESTS_FAILED=${failed}`);if(failed)throw new Error(failures.join('\n'));
 }finally{resetRazorpayInstance();await stopTestEnvironment();}}
main().catch(e=>{console.error(e);process.exitCode=1});
