process.env.NODE_ENV='test';process.env.PAYMENT_PROVIDER_MODE='mock';process.env.PAYOUT_PROVIDER_MODE='mock';
import assert from 'node:assert/strict';import request from 'supertest';import {readFile,access} from 'node:fs/promises';import path from 'node:path';
import {startReplicaSetTestEnvironment,stopTestEnvironment,createTestApp} from './helpers/testEnvironment.js';import {validateProductionEnvironment} from '../src/config/productionConfigValidator.js';
let pass=0,fail=0;const failures=[];const counts={configuration:0,security:0,operations:0,journeyContracts:0};async function t(group,name,fn){try{await fn();pass++;counts[group]++;console.log(`PASS ${group} ${name}`)}catch(e){fail++;failures.push(`${group}/${name}: ${e.message}`);console.error(`FAIL ${group} ${name}: ${e.message}`)}}
const base={NODE_ENV:'production',PORT:'5001',MONGODB_URI:'mongodb+srv://cluster.invalid/app',FRONTEND_URL:'https://app.marketplace.invalid',CUSTOMER_APP_URL:'https://app.marketplace.invalid',CORS_ALLOWED_ORIGINS:'https://app.marketplace.invalid,https://admin.marketplace.invalid',JWT_ACCESS_SECRET:'a'.repeat(48),JWT_REFRESH_SECRET:'b'.repeat(48),LOG_LEVEL:'info',TRUST_PROXY:'1',PAYMENT_PROVIDER_MODE:'live',PAYMENT_ENABLED:'true',RAZORPAY_KEY_ID:'rzp_live_abcdefghijkl',RAZORPAY_KEY_SECRET:'c'.repeat(32),RAZORPAY_WEBHOOK_SECRET:'d'.repeat(32),PAYOUT_ENABLED:'false',GOOGLE_OAUTH_ENABLED:'false',APPLE_OAUTH_ENABLED:'false',STORAGE_ENABLED:'false',EMAIL_ENABLED:'false'};
const bad=(key,value)=>assert.throws(()=>validateProductionEnvironment({...base,[key]:value}),e=>e.code==='PRODUCTION_CONFIG_INVALID');
await t('configuration','valid production baseline accepted',()=>assert.equal(validateProductionEnvironment(base).valid,true));
for(const [name,key,value] of [['missing port','PORT',''],['missing Mongo URI','MONGODB_URI',''],['missing access secret','JWT_ACCESS_SECRET',''],['weak access secret','JWT_ACCESS_SECRET','weak'],['placeholder access secret','JWT_ACCESS_SECRET','your_jwt_access_secret_key_change_me'],['weak refresh secret','JWT_REFRESH_SECRET','tiny'],['identical JWT secrets','JWT_REFRESH_SECRET',base.JWT_ACCESS_SECRET],['localhost frontend','FRONTEND_URL','http://localhost:5173'],['HTTP frontend','FRONTEND_URL','http://app.invalid'],['wildcard CORS','CORS_ALLOWED_ORIGINS','*'],['localhost CORS','CORS_ALLOWED_ORIGINS','http://localhost:5173'],['missing log level','LOG_LEVEL',''],['missing trust proxy','TRUST_PROXY',''],['unsafe trust proxy','TRUST_PROXY','99'],['mock payment','PAYMENT_PROVIDER_MODE','mock'],['missing payment secret','RAZORPAY_KEY_SECRET',''],['placeholder webhook secret','RAZORPAY_WEBHOOK_SECRET','your_webhook_secret'],['enabled Google missing config','GOOGLE_OAUTH_ENABLED','true'],['enabled Apple missing config','APPLE_OAUTH_ENABLED','true']])await t('configuration',name,()=>bad(key,value));

await t('operations','CI runs frontend production build',async()=>assert.ok((await readFile(path.resolve(process.cwd(),'../.github/workflows/ci.yml'),'utf8')).includes('npm run build')));
await startReplicaSetTestEnvironment();try{const app=await createTestApp();
 const health=await request(app).get('/health');await t('security','health returns 200',()=>assert.equal(health.status,200));await t('security','health exposes no environment secrets',()=>assert.ok(!JSON.stringify(health.body).match(/jwt|mongodb|secret|cookie/i)));const ready=await request(app).get('/ready');await t('security','readiness returns 200 with connected replica set',()=>assert.equal(ready.status,200));await t('security','readiness reports database up',()=>assert.equal(ready.body.database,'UP'));
 await t('security','Helmet nosniff header',()=>assert.equal(health.headers['x-content-type-options'],'nosniff'));await t('security','Helmet frame protection',()=>assert.ok(health.headers['x-frame-options']));await t('security','Helmet referrer policy',()=>assert.ok(health.headers['referrer-policy']));await t('security','Helmet opener policy',()=>assert.ok(health.headers['cross-origin-opener-policy']));await t('security','Helmet resource policy',()=>assert.ok(health.headers['cross-origin-resource-policy']));
 await t('security','allowed CORS origin accepted',async()=>assert.equal((await request(app).options('/api/categories').set('Origin','http://test.local').set('Access-Control-Request-Method','GET')).status,204));await t('security','unapproved CORS origin rejected',async()=>assert.ok((await request(app).get('/health').set('Origin','https://evil.invalid')).status>=400));await t('security','null CORS origin rejected',async()=>assert.ok((await request(app).get('/health').set('Origin','null')).status>=400));await t('security','suffix origin attack rejected',async()=>assert.ok((await request(app).get('/health').set('Origin','http://test.local.evil.invalid')).status>=400));await t('security','prefix origin attack rejected',async()=>assert.ok((await request(app).get('/health').set('Origin','http://evil.test.local')).status>=400));
 process.env.CSRF_ENFORCE_IN_TEST='true';await t('security','cookie unsafe request without origin rejected',async()=>assert.equal((await request(app).post('/api/v1/support').set('Cookie','access_token=fake').send({})).status,403));await t('security','cookie unsafe request evil origin rejected',async()=>assert.equal((await request(app).post('/api/v1/support').set('Cookie','access_token=fake').set('Origin','https://evil.invalid').send({})).status,403));await t('security','allowed browser origin reaches authentication',async()=>assert.equal((await request(app).post('/api/v1/support').set('Cookie','access_token=fake').set('Origin','http://test.local').send({})).status,401));delete process.env.CSRF_ENFORCE_IN_TEST;
 await t('security','oversized JSON rejected',async()=>assert.equal((await request(app).post('/api/auth/login').set('Content-Type','application/json').send({email:'a'.repeat(2200000)})).status,413));await t('security','unauthenticated notifications rejected',async()=>assert.equal((await request(app).get('/api/v1/notifications')).status,401));await t('security','unauthenticated support rejected',async()=>assert.equal((await request(app).get('/api/v1/support')).status,401));await t('security','unauthenticated chat mutation rejected',async()=>assert.equal((await request(app).post('/api/v1/chat/bookings/invalid/messages').send({text:{$ne:null}})).status,401));
 const root=path.resolve(process.cwd(),'..');const communicationFiles=['frontend/src/components/chat/Chat.jsx','frontend/src/components/chat/NotificationCentre.jsx','frontend/src/pages/SupportPortal.jsx','frontend/src/components/AdminSupportPanel.jsx','frontend/src/components/AdminChatModerationPanel.jsx'];const sources=await Promise.all(communicationFiles.map(file=>readFile(path.join(root,file),'utf8')));await t('security','communication UI has no dangerouslySetInnerHTML',()=>assert.ok(sources.every(x=>!x.includes('dangerouslySetInnerHTML'))));await t('security','communication UI has no token localStorage',()=>assert.ok(sources.every(x=>!/localStorage\.[^(]+\([^)]*(token|jwt)/i.test(x))));await t('security','communication URLs are environment driven',()=>assert.ok(sources.slice(0,2).every(x=>x.includes('import.meta.env'))));

 const models=['User','Booking','Message','Conversation','Notification','NotificationOutbox','SupportTicket'];for(const modelName of models)await t('operations',`${modelName} declares indexes`,async()=>{const {default:Model}=await import(`../src/models/${modelName}.js`);assert.ok(Model.schema.indexes().length>0)});
 await t('operations','health response is small',()=>assert.ok(Number(health.headers['content-length']||JSON.stringify(health.body).length)<1024));await t('operations','readiness response is small',()=>assert.ok(JSON.stringify(ready.body).length<2048));await t('operations','Docker backend definition exists',()=>access(path.join(root,'backend/Dockerfile')));await t('operations','Docker frontend definition exists',()=>access(path.join(root,'frontend/Dockerfile')));await t('operations','frontend SPA fallback configured',async()=>assert.ok((await readFile(path.join(root,'frontend/nginx.conf'),'utf8')).includes('try_files $uri /index.html')));await t('operations','frontend security CSP configured',async()=>assert.ok((await readFile(path.join(root,'frontend/nginx.conf'),'utf8')).includes('Content-Security-Policy')));await t('operations','Docker context excludes secrets',async()=>assert.ok((await readFile(path.join(root,'.dockerignore'),'utf8')).includes('**/.env*')));await t('operations','CI runs complete tests',async()=>assert.ok((await readFile(path.join(root,'.github/workflows/ci.yml'),'utf8')).includes('npm run test:all')));await t('operations','CI runs socket smoke',async()=>assert.ok((await readFile(path.join(root,'.github/workflows/ci.yml'),'utf8')).includes('test:socket:smoke')));

 const routes={customer:['frontend/src/pages/CustomerHome.jsx','frontend/src/pages/SupportPortal.jsx','frontend/src/components/chat/Chat.jsx'],worker:['frontend/src/pages/WorkerDashboard.jsx','frontend/src/pages/WorkerOnboarding.jsx'],admin:['frontend/src/pages/AdminDashboard.jsx','frontend/src/components/AdminSupportPanel.jsx','frontend/src/components/AdminChatModerationPanel.jsx']};for(const [role,files] of Object.entries(routes))for(const file of files)await t('journeyContracts',`${role} surface exists: ${path.basename(file)}`,()=>access(path.join(root,file)));
 const appSource=await readFile(path.join(root,'backend/src/app.js'),'utf8');for(const [name,mount] of [['auth','/api/auth'],['workers','/api/workers'],['bookings','/api/v1/bookings'],['pricing','/api/v1/pricing'],['payments','/api/v1/payments'],['refunds','/api/v1/refunds'],['reviews','/api/v1/reviews'],['chat','/api/v1/chat'],['notifications','/api/v1/notifications'],['support','/api/v1/support'],['admin','/api/v1/admin']])await t('journeyContracts',`${name} route mounted`,()=>assert.ok(appSource.includes(`'${mount}'`)));
}finally{await stopTestEnvironment();}
console.log(`READINESS_CONFIGURATION=${counts.configuration} READINESS_SECURITY=${counts.security} READINESS_OPERATIONS=${counts.operations} READINESS_JOURNEY_CONTRACTS=${counts.journeyContracts}`);console.log(`FINAL_READINESS_TESTS_EXECUTED=${pass+fail} FINAL_READINESS_TESTS_PASSED=${pass} FINAL_READINESS_TESTS_FAILED=${fail}`);if(pass+fail<80)throw new Error(`Readiness suite discovered only ${pass+fail} tests`);if(fail)throw new Error(failures.join('\n'));
