import crypto from 'crypto';
import User from '../models/User.js';
import RefreshToken from '../models/RefreshToken.js';
import WorkerProfile from '../models/WorkerProfile.js';
import AuditLog from '../models/AuditLog.js';
import { registerSchema, loginSchema } from '../utils/validation.js';
import { hashPassword, comparePassword, signAccessToken, signRefreshToken, verifyRefreshToken } from '../utils/authUtils.js';

const ACCESS_COOKIE='access_token', REFRESH_COOKIE='refreshToken';
const hashToken = token => crypto.createHash('sha256').update(token).digest('hex');
const cookies = req => Object.fromEntries(String(req.headers.cookie||'').split(';').map(v=>v.trim().split('=').map(decodeURIComponent)).filter(v=>v.length===2));
const cookieOptions = (maxAge,path='/') => ({httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'none':'lax',path,maxAge});
export const safeUser = user => ({id:user._id,name:user.name,email:user.email,role:user.role,status:user.status,emailVerified:!!user.emailVerified,phoneVerified:!!user.phoneVerified});
export const setSessionCookies = (res,accessToken,refreshToken) => {res.cookie(ACCESS_COOKIE,accessToken,cookieOptions(15*60*1000));res.cookie(REFRESH_COOKIE,refreshToken,cookieOptions(7*24*60*60*1000, '/'));};
export const clearSessionCookies = res => {res.clearCookie(ACCESS_COOKIE,cookieOptions(0));res.clearCookie(REFRESH_COOKIE,cookieOptions(0, '/'));};
export async function issueSession(user){const base={userId:user._id.toString(),role:user.role,email:user.email};const accessToken=signAccessToken({...base,tokenId:crypto.randomUUID()});const refreshToken=signRefreshToken({...base,tokenId:crypto.randomUUID()});await RefreshToken.create({userId:user._id,tokenHash:hashToken(refreshToken),expiresAt:new Date(Date.now()+7*24*60*60*1000)});return{accessToken,refreshToken};}
async function audit(user,action,req,after={}){await AuditLog.create({actor:user._id,action,resourceType:'User',resourceId:user._id.toString(),beforeSnapshot:{},afterSnapshot:after,ipAddress:req.ip,userAgent:req.get?.('user-agent'),requestId:req.requestId});}

export const register=async(req,res,next)=>{try{console.log("REGISTER API HIT");const data=registerSchema.parse(req.body);const [emailExists,phoneExists]=await Promise.all([User.exists({email:data.email}),User.exists({phone:data.phone})]);if(emailExists)return res.status(409).json({statusCode:409,errorCode:'EMAIL_EXISTS',field:'email',message:'This email address is already registered. Please sign in instead.'});if(phoneExists)return res.status(409).json({statusCode:409,errorCode:'PHONE_EXISTS',field:'phone',message:'This mobile number is already registered. Use another number or sign in.'});const user=await User.create({name:data.name,email:data.email,phone:data.phone,passwordHash:await hashPassword(data.password),role:data.role,status:'ACTIVE'});try{if(data.role==='WORKER')await WorkerProfile.create({userId:user._id,verificationStatus:'INCOMPLETE_PROFILE',isPubliclyVisible:false,isOnline:false});await audit(user,'AUTH_REGISTERED',req,{role:user.role});}catch(error){await User.deleteOne({_id:user._id});throw error;}return res.status(201).json({success:true,message:'Registration successful.',user:safeUser(user)});}catch(error){if(error?.code===11000){const field=error.keyPattern?.email?'email':'phone';return res.status(409).json({statusCode:409,errorCode:field==='email'?'EMAIL_EXISTS':'PHONE_EXISTS',field,message:field==='email'?'This email address is already registered. Please sign in instead.':'This mobile number is already registered. Use another number or sign in.'});}next(error);}};

export const login=async(req,res,next)=>{try{const {email,password}=loginSchema.parse(req.body);const user=await User.findOne({email}).select('+passwordHash');const valid=user&&await comparePassword(password,user.passwordHash);if(!valid){if(user){user.failedLoginAttempts+=1;if(user.failedLoginAttempts>=5){user.lockedUntil=new Date(Date.now()+60*60*1000);user.failedLoginAttempts=0;}await user.save();}return res.status(401).json({statusCode:401,errorCode:'INVALID_CREDENTIALS',message:'Invalid email or password.'});}if(user.lockedUntil&&user.lockedUntil>new Date())return res.status(423).json({statusCode:423,errorCode:'ACCOUNT_LOCKED',message:'Account is temporarily locked.'});if(user.status!=='ACTIVE')return res.status(403).json({statusCode:403,errorCode:'ACCOUNT_DISABLED',message:'This account is unavailable. Please contact support.'});user.failedLoginAttempts=0;user.lockedUntil=undefined;user.lastLoginAt=new Date();await user.save();const session=await issueSession(user);setSessionCookies(res,session.accessToken,session.refreshToken);await audit(user,'AUTH_LOGIN_SUCCEEDED',req,{role:user.role});return res.status(200).json({success:true,accessToken:session.accessToken,user:safeUser(user)});}catch(error){next(error);}};

export const refresh=async(req,res,next)=>{const token=cookies(req)[REFRESH_COOKIE]||req.body?.refreshToken;if(!token)return res.status(401).json({statusCode:401,errorCode:'REFRESH_TOKEN_REQUIRED',message:'Session token is required.'});try{verifyRefreshToken(token);const record=await RefreshToken.findOne({tokenHash:hashToken(token)});if(!record)return res.status(401).json({statusCode:401,errorCode:'INVALID_TOKEN',message:'Invalid session token.'});const user=await User.findById(record.userId);if(!user||user.status!=='ACTIVE')return res.status(403).json({statusCode:403,errorCode:'SESSION_REVOKED',message:'Session is unavailable.'});if(record.isUsed||record.isRevoked||record.expiresAt<new Date()){await RefreshToken.updateMany({userId:user._id},{isRevoked:true});clearSessionCookies(res);return res.status(403).json({statusCode:403,errorCode:'REUSE_ATTACK_DETECTED',message:'Session reuse detected. Please sign in again.'});}record.isUsed=true;const session=await issueSession(user);record.replacedByTokenHash=hashToken(session.refreshToken);await record.save();setSessionCookies(res,session.accessToken,session.refreshToken);return res.status(200).json({success:true,accessToken:session.accessToken,user:safeUser(user)});}catch(error){if(['JsonWebTokenError','TokenExpiredError'].includes(error.name))return res.status(401).json({statusCode:401,errorCode:'INVALID_TOKEN',message:'Invalid session token.'});next(error);}};

export const logout=async(req,res,next)=>{try{const token=cookies(req)[REFRESH_COOKIE]||req.body?.refreshToken;if(token)await RefreshToken.updateOne({tokenHash:hashToken(token)},{isRevoked:true});clearSessionCookies(res);return res.status(200).json({success:true,message:'Logout successful.'});}catch(error){next(error);}};
export const me=async(req,res,next)=>{try{const user=await User.findById(req.user.userId);if(!user)return res.status(401).json({statusCode:401,errorCode:'UNAUTHENTICATED',message:'Authentication required.'});return res.status(200).json({success:true,user:safeUser(user)});}catch(error){next(error);}};
