import mongoose from 'mongoose';import Review from '../models/Review.js';import ReviewReport from '../models/ReviewReport.js';import WorkerRatingAggregate from '../models/WorkerRatingAggregate.js';import AuditLog from '../models/AuditLog.js';import {evaluateReviewEligibility,reviewError} from '../services/ReviewEligibilityService.js';import ReviewService from '../services/ReviewService.js';import {moderateReview,resolveReport} from '../services/ReviewModerationService.js';import {verifyReviews,rebuildWorkerAggregate} from '../services/ReviewReconciliationService.js';import {publicReviewDto,ownerReviewDto,workerReviewDto,adminReviewDto} from '../utils/reviewDto.js';
const id=x=>{if(!mongoose.Types.ObjectId.isValid(x))throw reviewError('INVALID_OBJECT_ID','Invalid identifier.',400);return x;};const paging=q=>{const page=Math.max(1,Number(q.page)||1),limit=Math.min(50,Math.max(1,Number(q.limit)||10));return{page,limit,skip:(page-1)*limit};};const meta=req=>({ipAddress:req.ip,userAgent:req.headers['user-agent'],requestId:req.requestId});
export async function eligibility(req,res,next){try{const out=await evaluateReviewEligibility({bookingId:id(req.params.bookingId),user:req.user});await AuditLog.create({actor:req.user.userId,action:'REVIEW_ELIGIBILITY_CHECKED',resourceType:'Booking',resourceId:String(out.booking._id),afterSnapshot:{eligible:true,holdForDispute:out.holdForDispute}});res.json({success:true,eligible:true,holdForModeration:out.holdForDispute,expiresAt:new Date(new Date(out.booking.completedAt||out.booking.updatedAt).getTime()+out.policy.reviewWindowDays*86400000),allowedTags:out.policy.allowedTags});}catch(e){next(e);}}
export async function create(req,res,next){try{const out=await ReviewService.createReview({user:req.user,body:req.body,idempotencyKey:req.headers['idempotency-key'],requestMeta:meta(req)});const review=await Review.findById(out.review._id);res.status(out.idempotent?200:201).json({success:true,idempotent:out.idempotent,review:ownerReviewDto(review)});}catch(e){next(e);}}
export async function mine(req,res,next){try{const p=paging(req.query),filter={reviewerId:req.user.userId};const [rows,total]=await Promise.all([Review.find(filter).sort({createdAt:-1}).skip(p.skip).limit(p.limit),Review.countDocuments(filter)]);res.json({success:true,reviews:rows.map(ownerReviewDto),pagination:{...p,total,totalPages:Math.ceil(total/p.limit)}});}catch(e){next(e);}}
export async function getMine(req,res,next){try{const r=await Review.findOne({_id:id(req.params.id),reviewerId:req.user.userId});if(!r)throw reviewError('REVIEW_NOT_FOUND','Review not found.',404);res.json({success:true,review:ownerReviewDto(r)});}catch(e){next(e);}}
export async function edit(req,res,next){try{const r=await ReviewService.editReview({user:req.user,reviewId:id(req.params.id),body:req.body,requestMeta:meta(req)});res.json({success:true,review:ownerReviewDto(r)});}catch(e){next(e);}}
export async function remove(req,res,next){try{const r=await ReviewService.requestRemoval({user:req.user,reviewId:id(req.params.id),reasonCode:req.body.reasonCode,requestMeta:meta(req)});res.json({success:true,review:ownerReviewDto(r)});}catch(e){next(e);}}
export async function report(req,res,next){try{const r=await ReviewService.reportReview({user:req.user,reviewId:id(req.params.id),body:req.body,requestMeta:meta(req)});res.status(201).json({success:true,report:{id:String(r._id),reasonCode:r.reasonCode,status:r.status,createdAt:r.createdAt}});}catch(e){next(e);}}
export async function publicList(req,res,next){try{const p=paging(req.query),sortMap={recent:{createdAt:-1},highest:{rating:-1,createdAt:-1},lowest:{rating:1,createdAt:-1}},sort=sortMap[req.query.sort||'recent'];if(!sort)throw reviewError('INVALID_SORT','Unsupported review sort.',400);const filter={workerId:id(req.params.workerId),status:'PUBLISHED'};const [rows,total]=await Promise.all([Review.find(filter).populate('customerId','name').sort(sort).skip(p.skip).limit(p.limit),Review.countDocuments(filter)]);res.json({success:true,reviews:rows.map(publicReviewDto),pagination:{page:p.page,limit:p.limit,total,totalPages:Math.ceil(total/p.limit)}});}catch(e){next(e);}}
export async function summary(req,res,next){try{const workerId=id(req.params.workerId||req.user.userId),a=await WorkerRatingAggregate.findOne({workerId}).lean();res.json({success:true,summary:a?{averageRating:a.averageRating,ratingCount:a.ratingCount,verifiedReviewCount:a.verifiedReviewCount,ratingDistribution:a.ratingDistribution,lastReviewedAt:a.lastReviewedAt}:{averageRating:null,ratingCount:0,verifiedReviewCount:0,ratingDistribution:{oneStar:0,twoStar:0,threeStar:0,fourStar:0,fiveStar:0},lastReviewedAt:null}});}catch(e){next(e);}}
export async function workerList(req,res,next){try{const p=paging(req.query),filter={workerId:req.user.userId,status:{$in:['PUBLISHED','PENDING_MODERATION','HIDDEN']}};const [rows,total]=await Promise.all([Review.find(filter).populate('customerId','name').sort({createdAt:-1}).skip(p.skip).limit(p.limit),Review.countDocuments(filter)]);res.json({success:true,reviews:rows.map(workerReviewDto),pagination:{page:p.page,limit:p.limit,total}});}catch(e){next(e);}}
export async function workerGet(req,res,next){try{const r=await Review.findOne({_id:id(req.params.id),workerId:req.user.userId}).populate('customerId','name');if(!r)throw reviewError('REVIEW_NOT_FOUND','Review not found.',404);res.json({success:true,review:workerReviewDto(r)});}catch(e){next(e);}}
export async function respond(req,res,next){try{const r=await ReviewService.respondToReview({user:req.user,reviewId:id(req.params.id),text:req.body.response,edit:req.method==='PATCH',requestMeta:meta(req)});res.json({success:true,review:workerReviewDto(r)});}catch(e){next(e);}}
export async function adminList(req,res,next){try{const p=paging(req.query),filter={};if(req.query.status)filter.status=req.query.status;if(req.query.moderationStatus)filter.moderationStatus=req.query.moderationStatus;if(req.query.rating)filter.rating=Number(req.query.rating);if(req.query.workerId)filter.workerId=id(req.query.workerId);const [rows,total]=await Promise.all([Review.find(filter).populate('customerId','name').populate('workerId','name').sort({reportCount:-1,createdAt:-1}).skip(p.skip).limit(p.limit),Review.countDocuments(filter)]);res.json({success:true,reviews:rows.map(adminReviewDto),pagination:{page:p.page,limit:p.limit,total}});}catch(e){next(e);}}
export async function adminGet(req,res,next){try{const r=await Review.findById(id(req.params.id)).populate('customerId','name').populate('workerId','name');if(!r)throw reviewError('REVIEW_NOT_FOUND','Review not found.',404);const timeline=await AuditLog.find({resourceType:'Review',resourceId:String(r._id)}).sort({createdAt:1}).select('action createdAt actor');res.json({success:true,review:adminReviewDto(r),auditTimeline:timeline});}catch(e){next(e);}}
export async function moderate(req,res,next){try{const r=await moderateReview({reviewId:id(req.params.id),action:req.reviewAction,reasonCode:req.body.reasonCode,actor:req.user,requestMeta:meta(req)});res.json({success:true,review:adminReviewDto(r)});}catch(e){next(e);}}
export async function reports(req,res,next){try{const p=paging(req.query),filter=req.query.status?{status:req.query.status}:{},rows=await ReviewReport.find(filter).populate('reviewId','rating title status').sort({createdAt:-1}).skip(p.skip).limit(p.limit);res.json({success:true,reports:rows.map(r=>({id:String(r._id),review:r.reviewId,reasonCode:r.reasonCode,status:r.status,createdAt:r.createdAt}))});}catch(e){next(e);}}
export async function reportGet(req,res,next){try{const r=await ReviewReport.findById(id(req.params.id)).populate('reviewId','rating title comment status');if(!r)throw reviewError('REPORT_NOT_FOUND','Report not found.',404);res.json({success:true,report:{id:String(r._id),review:r.reviewId,reasonCode:r.reasonCode,descriptionSafe:r.descriptionSafe,status:r.status,resolutionCode:r.resolutionCode}});}catch(e){next(e);}}
export async function reportResolve(req,res,next){try{const r=await resolveReport({reportId:id(req.params.id),actor:req.user,resolutionCode:req.body.resolutionCode,reject:req.reportReject});res.json({success:true,report:{id:String(r._id),status:r.status,resolutionCode:r.resolutionCode}});}catch(e){next(e);}}
export async function reconcile(req,res,next){try{res.json({success:true,...await verifyReviews({workerId:req.query.workerId})});}catch(e){next(e);}}
export async function rebuild(req,res,next){try{const workerId=id(req.params.workerId),aggregate=await rebuildWorkerAggregate(workerId);await AuditLog.create({actor:req.user.userId,action:'REVIEW_AGGREGATE_REBUILT',resourceType:'WorkerRatingAggregate',resourceId:String(workerId),afterSnapshot:{ratingCount:aggregate.ratingCount,ratingSum:aggregate.ratingSum}});res.json({success:true,aggregate});}catch(e){next(e);}}
